# Copyright 2021 Huawei Technologies Co., Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ============================================================================

MS_ALL:
    include/api
    mindspore/core
    mindspore/ccsrc/cxx_api
    mindspore/ccsrc/backend/common
    mindspore/ccsrc/plugin/device/cpu/kernel/nnacl
    mindspore/ccsrc/minddata
    mindspore/ccsrc/CMakeLists.txt
    mindspore/lite/java
    mindspore/lite/src/train
    mindspore/lite/src/runtime/kernel/arm/fp32
    mindspore/lite/src/runtime/kernel/arm/fp32_grad
    mindspore/ccsrc/backend/kernel_compiler
    mindspore/ccsrc/fl
    mindspore/ccsrc/ps
MS_CLOUD:
    mindspore/python
    mindspore/ccsrc
    tests/st
MS_LITE:
    include/c_api
    include/api/allocator.h
    include/api/delegate.h
    include/api/kernel.h
    include/api/model_parallel_runner.h
    mindspore/lite/
    cmake/package_lite.cmake
MS_CLOUD_UT:
    tests/ut
MS_CLOUD_UT_CPP:
    tests/ut/cpp
MS_CLOUD_UT_PYTHON:
    tests/ut/python
MS_CLOUD_ST_ASCEND:
    tests/st/ops/ascend
MS_CLOUD_ST_GPU:
    tests/st/ops/gpu
MS_CLOUD_ST_CPU:
    tests/st/ops/cpu
MS_CI:
    .jenkins
    .clang-format
MS_DOCS:
    docker
    docs
    scripts
    README.md
    Readme.md
    readme.md
    README_CN.md
    RELEASE.md
    release.md
    PULL_REQUEST_TEMPLATE.md
    CONTRIBUTING.md
    LICENSE
    NOTICE
    SECURITY.md
    Third_Party_Open_Source_Software
